#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/nash

PRODUCT_COPY_FILES += \
    vendor/motorola/nash/proprietary/system/etc/firmware/upd-00000126-00001001-fed70128-fffe0001-02.tftf:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/upd-00000126-00001001-fed70128-fffe0001-02.tftf \
    vendor/motorola/nash/proprietary/system/etc/permissions/com.motorola.aov.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.aov.xml \
    vendor/motorola/nash/proprietary/system/etc/permissions/com.motorola.mod.protocols.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.mod.protocols.xml \
    vendor/motorola/nash/proprietary/system/etc/permissions/com.motorola.mod.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.mod.xml \
    vendor/motorola/nash/proprietary/system/etc/permissions/com.motorola.mod_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.mod_config.xml \
    vendor/motorola/nash/proprietary/system/etc/permissions/com.motorola.mod_v2.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.mod_v2.xml \
    vendor/motorola/nash/proprietary/system/etc/permissions/com.motorola.moto.permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.moto.permissions.xml \
    vendor/motorola/nash/proprietary/system/etc/permissions/privapp-permissions-com.motorola.modservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.motorola.modservice.xml \
    vendor/motorola/nash/proprietary/system/etc/permissions/privapp-permissions-com.motorola.projectormod.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.motorola.projectormod.xml \
    vendor/motorola/nash/proprietary/system/etc/sysconfig/hiddenapi-whitelist-com.motorola.camera2.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/hiddenapi-whitelist-com.motorola.camera2.xml \
    vendor/motorola/nash/proprietary/system/etc/sysconfig/hiddenapi-whitelist-com.motorola.modservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/hiddenapi-whitelist-com.motorola.modservice.xml \
    vendor/motorola/nash/proprietary/system/etc/sysconfig/hiddenapi-whitelist-com.motorola.projectormod.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/hiddenapi-whitelist-com.motorola.projectormod.xml \
    vendor/motorola/nash/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/nash/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/nash/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/nash/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/nash/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/nash/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/nash/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/nash/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-nash.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-nash.rc \
    vendor/motorola/nash/proprietary/vendor/etc/init/motorola.hardware.health@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.health@1.0-service.rc \
    vendor/motorola/nash/proprietary/vendor/etc/permissions/com.motorola.camera2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.motorola.camera2.xml \
    vendor/motorola/nash/proprietary/vendor/etc/permissions/com.motorola.moto.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.motorola.moto.xml \
    vendor/motorola/nash/proprietary/vendor/etc/permissions/com.motorola.motodisplay.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.motorola.motodisplay.xml \
    vendor/motorola/nash/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_cmd_smd_QHD_546_g.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_cmd_smd_QHD_546_g.xml \
    vendor/motorola/nash/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_cmd_smd_QHD_546_p.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_cmd_smd_QHD_546_p.xml \
    vendor/motorola/nash/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/motorola/nash/proprietary/vendor/etc/zaf/zaf_imx386.json:$(TARGET_COPY_OUT_VENDOR)/etc/zaf/zaf_imx386.json \
    vendor/motorola/nash/proprietary/vendor/etc/zaf/zaf_imx386_mono.json:$(TARGET_COPY_OUT_VENDOR)/etc/zaf/zaf_imx386_mono.json \
    vendor/motorola/nash/proprietary/vendor/etc/zaf/zaf_mot_s5k2l7sa.json:$(TARGET_COPY_OUT_VENDOR)/etc/zaf/zaf_mot_s5k2l7sa.json \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/motorola/nash/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw

PRODUCT_PACKAGES += \
    libmodhw \
    libvibratorhw \
    motorola.hardware.vibrator@1.0 \
    com.motorola.mod@1.0_vendor \
    gatekeeper.msm8998 \
    keystore.msm8998 \
    vulkan.msm8998 \
    libQSEEComAPI \
    libdualcameraddm \
    libiio \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmodmanager \
    libsensor1 \
    libsensor_reg \
    libsns_low_lat_stream_stub \
    libvideobokeh \
    sensor_calibrate \
    sensors.iio \
    sensors.ssc \
    sensors.tof \
    audio.primary.msm8998-moto \
    camera.msm8998 \
    libSonyDefocus \
    libS5k2l7Pdaf \
    libS5k2l7PdafCamif \
    lib_mot_app6_metadata \
    lib_mot_led_calibration \
    lib_motsensorlistener \
    libactuator_mot_ak7371 \
    libadsp_hvx_callback_skel \
    libadsp_hvx_stub \
    libcdsprpc \
    libchromaflash \
    libchromatix_imx386_4k_video_3a \
    libchromatix_imx386_common \
    libchromatix_imx386_cpp_hfr_120 \
    libchromatix_imx386_cpp_hfr_240 \
    libchromatix_imx386_cpp_hfr_60 \
    libchromatix_imx386_cpp_liveshot \
    libchromatix_imx386_cpp_snapshot \
    libchromatix_imx386_cpp_snapshot_custom \
    libchromatix_imx386_cpp_video \
    libchromatix_imx386_cpp_video_4k \
    libchromatix_imx386_default_video \
    libchromatix_imx386_default_video_3a \
    libchromatix_imx386_hfr_120 \
    libchromatix_imx386_hfr_120_3a \
    libchromatix_imx386_hfr_240 \
    libchromatix_imx386_hfr_240_3a \
    libchromatix_imx386_hfr_60 \
    libchromatix_imx386_hfr_60_3a \
    libchromatix_imx386_mono_4k_video_3a \
    libchromatix_imx386_mono_common \
    libchromatix_imx386_mono_cpp_hfr_120 \
    libchromatix_imx386_mono_cpp_hfr_240 \
    libchromatix_imx386_mono_cpp_hfr_60 \
    libchromatix_imx386_mono_cpp_liveshot \
    libchromatix_imx386_mono_cpp_snapshot \
    libchromatix_imx386_mono_cpp_snapshot_custom \
    libchromatix_imx386_mono_cpp_video \
    libchromatix_imx386_mono_cpp_video_4k \
    libchromatix_imx386_mono_default_video \
    libchromatix_imx386_mono_default_video_3a \
    libchromatix_imx386_mono_hfr_120 \
    libchromatix_imx386_mono_hfr_120_3a \
    libchromatix_imx386_mono_hfr_240 \
    libchromatix_imx386_mono_hfr_240_3a \
    libchromatix_imx386_mono_hfr_60 \
    libchromatix_imx386_mono_hfr_60_3a \
    libchromatix_imx386_mono_postproc \
    libchromatix_imx386_mono_snapshot \
    libchromatix_imx386_mono_video_4k \
    libchromatix_imx386_mono_zsl_preview_3a \
    libchromatix_imx386_postproc \
    libchromatix_imx386_snapshot \
    libchromatix_imx386_video_4k \
    libchromatix_imx386_zsl_preview_3a \
    libchromatix_mot_ov5695_common \
    libchromatix_mot_ov5695_cpp_hfr_120 \
    libchromatix_mot_ov5695_cpp_liveshot \
    libchromatix_mot_ov5695_cpp_snapshot \
    libchromatix_mot_ov5695_cpp_snapshot_custom \
    libchromatix_mot_ov5695_cpp_video \
    libchromatix_mot_ov5695_default_video \
    libchromatix_mot_ov5695_default_video_3a \
    libchromatix_mot_ov5695_hfr_120 \
    libchromatix_mot_ov5695_hfr_120_3a \
    libchromatix_mot_ov5695_postproc \
    libchromatix_mot_ov5695_snapshot \
    libchromatix_mot_ov5695_snapshot_3a \
    libchromatix_mot_s5k2l7sa_1080p_preview_3a \
    libchromatix_mot_s5k2l7sa_1080p_video_3a \
    libchromatix_mot_s5k2l7sa_4k_preview_3a \
    libchromatix_mot_s5k2l7sa_4k_video_3a \
    libchromatix_mot_s5k2l7sa_common \
    libchromatix_mot_s5k2l7sa_cpp_hfr_120 \
    libchromatix_mot_s5k2l7sa_cpp_hfr_240 \
    libchromatix_mot_s5k2l7sa_cpp_hfr_60 \
    libchromatix_mot_s5k2l7sa_cpp_liveshot \
    libchromatix_mot_s5k2l7sa_cpp_preview \
    libchromatix_mot_s5k2l7sa_cpp_snapshot \
    libchromatix_mot_s5k2l7sa_cpp_video \
    libchromatix_mot_s5k2l7sa_cpp_video_4k \
    libchromatix_mot_s5k2l7sa_default_preview_3a \
    libchromatix_mot_s5k2l7sa_default_video \
    libchromatix_mot_s5k2l7sa_default_video_3a \
    libchromatix_mot_s5k2l7sa_fullsize_preview_3a \
    libchromatix_mot_s5k2l7sa_fullsize_video_3a \
    libchromatix_mot_s5k2l7sa_hfr_120 \
    libchromatix_mot_s5k2l7sa_hfr_120_3a \
    libchromatix_mot_s5k2l7sa_hfr_240 \
    libchromatix_mot_s5k2l7sa_hfr_240_3a \
    libchromatix_mot_s5k2l7sa_hfr_60 \
    libchromatix_mot_s5k2l7sa_hfr_60_3a \
    libchromatix_mot_s5k2l7sa_postproc \
    libchromatix_mot_s5k2l7sa_preview \
    libchromatix_mot_s5k2l7sa_snapshot \
    libchromatix_mot_s5k2l7sa_video_4k \
    libchromatix_mot_s5k3p8sp_4m_cpp_snapshot \
    libchromatix_mot_s5k3p8sp_common \
    libchromatix_mot_s5k3p8sp_cpp_hfr_120 \
    libchromatix_mot_s5k3p8sp_cpp_liveshot \
    libchromatix_mot_s5k3p8sp_cpp_preview \
    libchromatix_mot_s5k3p8sp_cpp_snapshot \
    libchromatix_mot_s5k3p8sp_cpp_video \
    libchromatix_mot_s5k3p8sp_default_preview_3a \
    libchromatix_mot_s5k3p8sp_default_video_3a \
    libchromatix_mot_s5k3p8sp_hfr_120 \
    libchromatix_mot_s5k3p8sp_hfr_120_3a \
    libchromatix_mot_s5k3p8sp_postproc \
    libchromatix_mot_s5k3p8sp_preview \
    libchromatix_mot_s5k3p8sp_snapshot \
    libchromatix_mot_s5k4h8_aux_common \
    libchromatix_mot_s5k4h8_aux_cpp_hfr_120 \
    libchromatix_mot_s5k4h8_aux_cpp_hfr_60 \
    libchromatix_mot_s5k4h8_aux_cpp_liveshot \
    libchromatix_mot_s5k4h8_aux_cpp_preview \
    libchromatix_mot_s5k4h8_aux_cpp_snapshot \
    libchromatix_mot_s5k4h8_aux_cpp_video_full \
    libchromatix_mot_s5k4h8_aux_hfr_120 \
    libchromatix_mot_s5k4h8_aux_hfr_120_3a \
    libchromatix_mot_s5k4h8_aux_hfr_60 \
    libchromatix_mot_s5k4h8_aux_hfr_60_3a \
    libchromatix_mot_s5k4h8_aux_postproc \
    libchromatix_mot_s5k4h8_aux_snapshot \
    libchromatix_mot_s5k4h8_aux_video_full \
    libchromatix_mot_s5k4h8_aux_zsl_preview_3a \
    libchromatix_mot_s5k4h8_aux_zsl_video_3a \
    libchromatix_mot_s5k4h8_common \
    libchromatix_mot_s5k4h8_cpp_hfr_120 \
    libchromatix_mot_s5k4h8_cpp_liveshot \
    libchromatix_mot_s5k4h8_cpp_preview \
    libchromatix_mot_s5k4h8_cpp_snapshot \
    libchromatix_mot_s5k4h8_cpp_video_full \
    libchromatix_mot_s5k4h8_hfr_120 \
    libchromatix_mot_s5k4h8_hfr_120_3a \
    libchromatix_mot_s5k4h8_postproc \
    libchromatix_mot_s5k4h8_snapshot \
    libchromatix_mot_s5k4h8_video_full \
    libchromatix_mot_s5k4h8_zsl_preview_3a \
    libchromatix_mot_s5k4h8_zsl_video_3a \
    libcppf \
    libeqservicebridge \
    libfastcvadsp_stub \
    libflash_aw3643_front \
    libflash_aw3643_rear \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmcf-qc-fd-offline \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_chromaflash_lib \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_gt24c128b_mono_eeprom \
    libmmcamera_gt24c128b_rgb_eeprom \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx386 \
    libmmcamera_imx386_mono \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_mot_ov5695 \
    libmmcamera_mot_ov5695_eeprom \
    libmmcamera_mot_s5k2l7sa \
    libmmcamera_mot_s5k2l7sa_eeprom \
    libmmcamera_mot_s5k3p8sp \
    libmmcamera_mot_s5k3p8sp_eeprom \
    libmmcamera_optizoom_lib \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k4h8 \
    libmmcamera_s5k4h8_aux \
    libmmcamera_s5k4h8_eeprom \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_trueportrait_lib \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_ubifocus_lib \
    libmmcamera_vstab_module \
    libmmjpeg \
    libmmjpeg_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmot_afd \
    libmot_lux_standardization \
    libmotaudioutils \
    liboptizoom \
    libpn553_fw \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libscveBlobDescriptor \
    libscveBlobDescriptor_stub \
    libscveCommon \
    libscveCommon_stub \
    libscveFaceRecognition \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libscvePanorama \
    libscvePanorama_lite \
    libseemore \
    libtinyalsa-moto \
    libtinycompress \
    libtinycompress_vendor \
    libtrueportrait \
    libubifocus \
    libunshorten \
    libzaf_algs \
    libzaf_core \
    motorola.hardware.audio.eqservice@1.0_vendor \
    libmmieffectswrapper \
    libspeakerbundle \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    libGPreqcancel \
    libGPreqcancel_svc \
    libSecureUILib \
    libStDrvInt \
    libdrmfs \
    libdrmtime \
    libhdcpsrm \
    liboemcrypto \
    libqisl \
    librpmb \
    libsecureui_svcsock \
    libspl \
    libssd \
    libvl53l1_daemon \
    vendor.qti.hardware.tui_comm@1.0 \
    libsns_low_lat_stream_skel \
    libvpp_frc \
    libvpp_svc_skel \
    ModFmwkProxyService \
    ModService \
    ProjectorApp \
    charge_only_mode \
    android.hardware.biometrics.fingerprint@2.1-fpcservice \
    motorola.hardware.health@1.0-service \
    qseecomd \
    sensors.qti \
    vl53l1_daemon

PRODUCT_PACKAGES += \
    system_priv-app_ModFmwkProxyService_lib_arm64_libmodhw_so \
    system_priv-app_ModFmwkProxyService_lib_arm64_libvibratorhw_so
